# docker-compose.yml

version: '3.8'

services:
  svelte-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"  # Map port 80 in the container to port 8080 on the host
    restart: always
